language: go

# `sudo: required` is the default for repositories enabled before 2015 (we don't need it and it's slower)
dist: bionic
sudo: false

# https://docs.travis-ci.com/user/database-setup/
# Some of the db unit tests require redis on 127.0.0.0:6379
services:
- redis-server

# Compile with go 1.10 (or newer). It takes a long time to install `tip`
go:
  - 1.13.x

env:
  - GO111MODULE=on

# Only compute the build status for PRs in travis
branches:
  only:
    - master

# install step default is `go get ./...`
# script default is `go test ./...`
# (Could include apns-test.sh, but that doesn't have expected output written yet)
script:
  - go build
  - ./govet.sh
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  # run golangci-lint checks from .golangci.yml
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)
